# Deployment groups
- id: kvm-host
  type: group
  version: &task_engine_version 2.0.0
  role: [kvm-host]
  requires: [deploy_start]
  required_for: [deploy_end]
  tasks: &common_tasks
    - hiera
    - setup_repositories
    - fuel_pkgs
    - globals
    - tools
    - logging
    - netconfig
    - hosts
    - firewall
  parameters:
    strategy:
      type: one_by_one

# Deployment tasks
- id: kvm_depended_packages
  type: puppet
  version: *task_engine_version
  groups: [kvm-host]
  required_for : [kvm_plugin]
  requires: *common_tasks
  parameters:
    puppet_manifest: "puppet/manifests/packages.pp"
    puppet_modules: "puppet/modules/:/etc/puppet/modules/"
    timeout: 1200

- id: kvm_plugin
  type: puppet
  version: *task_engine_version
  groups: [kvm-host]
  required_for : [deploy_end]
  requires: [kvm_depended_packages]
  parameters:
    puppet_manifest: "puppet/manifests/kvm.pp"
    puppet_modules: "puppet/modules/:/etc/puppet/modules/"
    timeout: 1200

